### ISSUE TITLE
Milky Way disappears.

### ISSUE THREAD

**Issue by 1010todd** [kestrel1110/Exporianes#1]
map.txt

`galaxy "Milky Way"
    pos 0 0
    sprite og_res/ui/galaxy`

Excuse me?
![whotfstolemygalaxy](https://user-images.githubusercontent.com/19187937/120112456-25eab900-c1a0-11eb-8edc-7d32b2e7fc63.PNG)

**Comment by kestrel1110** [comment]
Issue should be fixed in the release I'm about to create, that was something I created in development stages of the map.
