### ISSUE TITLE
Dyson sphere all over the place.

### ISSUE THREAD

**Issue by Maddremor** [kestrel1110/Exporianes#3]
TL;DR: Author ship very big and distracting.

As a semi casual player, I've not had the opportunity to actually explore the meat of the content in this mod, but my first impression being an author ship turning up and covering the entire screen and everything thereon isn't super great. Could you limit the areas the ship travels or make a smaller version to be more discreet?

**Comment by kestrel1110** [comment]
Yeah I'm gonna work on reducing the frequency, for some reason it is showing up all the time.

**Comment by kestrel1110** [comment]
It's fixed FYI
